use air_core::{AirModule, DetailedTypeKind, StateAction, TypeSpec, Workflow};
use air_linker::{resolve_module_path, ModuleStore, RunPlan};
use std::collections::BTreeMap;
use std::path::Path;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum OpenAiAgentsJsBackendError {
    #[error("OpenAI Agents JS semantic backend only supports state_machine workflow lowering")]
    UnsupportedWorkflow,

    #[error("OpenAI Agents JS semantic backend requires at least one model_call action")]
    MissingModelCall,

    #[error("OpenAI Agents JS semantic backend currently supports at most one tool_call action")]
    TooManyToolCalls,

    #[error("failed to parse AIR module: {0}")]
    ModuleParse(#[from] air_parser::ParseError),

    #[error(transparent)]
    Linker(#[from] air_linker::LinkerError),

    #[error("failed to serialize JSON: {0}")]
    Json(#[from] serde_json::Error),

    #[error("run plan references unknown module {0}")]
    UnknownModule(String),

    #[error("module {module} failed verification: {diagnostics:?}")]
    ModuleVerify {
        module: String,
        diagnostics: Vec<air_core::Diagnostic>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SemanticPlan {
    model_alias: String,
    tool_name: Option<String>,
    primary_input: String,
    output_field: Option<String>,
    output_contract: String,
}

pub fn lower_module(module: &AirModule) -> Result<String, OpenAiAgentsJsBackendError> {
    let plan = semantic_plan(module)?;
    let mut output = String::new();
    push_prelude(&mut output, module);
    output.push_str(&format!(
        "const AIR_MODULE = {};\n\n",
        serde_json::to_string_pretty(module)?
    ));
    push_runtime_helpers(&mut output);
    push_main(&mut output, module, &plan);
    Ok(output)
}

pub fn lower_run_plan_strict(
    plan: &RunPlan,
    store: &ModuleStore,
    base_dir: impl AsRef<Path>,
) -> Result<String, OpenAiAgentsJsBackendError> {
    let base_dir = base_dir.as_ref();
    let mut modules = BTreeMap::new();

    for node in &plan.nodes {
        let module_ref = store
            .modules
            .get(&node.module)
            .ok_or_else(|| OpenAiAgentsJsBackendError::UnknownModule(node.module.clone()))?;
        let path = resolve_module_path(base_dir, &node.module, &module_ref.path)?;
        let module = air_parser::parse_air_file(path)?;
        let verification = air_verify::verify(&module);
        if !verification.is_success() {
            return Err(OpenAiAgentsJsBackendError::ModuleVerify {
                module: node.module.clone(),
                diagnostics: verification.diagnostics,
            });
        }
        modules.insert(node.id.clone(), module);
    }
    if let Some(dynamic) = &plan.dynamic {
        for fanout in &dynamic.fanouts {
            if modules.contains_key(&fanout.module) {
                continue;
            }
            let module_ref = store
                .modules
                .get(&fanout.module)
                .ok_or_else(|| OpenAiAgentsJsBackendError::UnknownModule(fanout.module.clone()))?;
            let path = resolve_module_path(base_dir, &fanout.module, &module_ref.path)?;
            let module = air_parser::parse_air_file(path)?;
            let verification = air_verify::verify(&module);
            if !verification.is_success() {
                return Err(OpenAiAgentsJsBackendError::ModuleVerify {
                    module: fanout.module.clone(),
                    diagnostics: verification.diagnostics,
                });
            }
            modules.insert(fanout.module.clone(), module);
        }
    }

    let mut output = String::new();
    output.push_str("// Generated by AIR OpenAI JS strict run-plan backend.\n");
    output
        .push_str("// This preserves RunPlan module order and per-module state-machine actions.\n");
    output.push_str(&format!(
        "// Source run plan: {} {}\n\n",
        plan.plan.name, plan.plan.version
    ));
    output.push_str("import fs from 'node:fs';\n");
    output.push_str("import OpenAI from 'openai';\n\n");
    output.push_str(&format!(
        "const RUN_PLAN = {};\n",
        serde_json::to_string_pretty(plan)?
    ));
    output.push_str(&format!(
        "const MODULES = {};\n\n",
        serde_json::to_string_pretty(&modules)?
    ));
    push_strict_js_runtime(&mut output);
    Ok(output)
}

fn semantic_plan(module: &AirModule) -> Result<SemanticPlan, OpenAiAgentsJsBackendError> {
    let Workflow::StateMachine(workflow) = &module.workflow else {
        return Err(OpenAiAgentsJsBackendError::UnsupportedWorkflow);
    };

    let mut model_alias = None;
    let mut tool_name = None;
    let mut return_output = None;

    for action in workflow.rules.iter().flat_map(|rule| &rule.actions) {
        match action {
            StateAction::ModelCall { model, .. } if model_alias.is_none() => {
                model_alias = Some(model.clone());
            }
            StateAction::ToolCall { tool, .. } if tool_name.replace(tool.clone()).is_some() => {
                return Err(OpenAiAgentsJsBackendError::TooManyToolCalls);
            }
            StateAction::ToolCall { .. } => {}
            StateAction::ToolDispatch { .. } | StateAction::ToolBatchDispatch { .. } => {
                return Err(OpenAiAgentsJsBackendError::TooManyToolCalls);
            }
            StateAction::Return { output } if return_output.is_none() => {
                return_output = Some(output.clone());
            }
            _ => {}
        }
    }

    let Some(model_alias) = model_alias else {
        return Err(OpenAiAgentsJsBackendError::MissingModelCall);
    };

    let primary_input = module
        .inputs
        .keys()
        .next()
        .cloned()
        .unwrap_or_else(|| "input".to_string());

    Ok(SemanticPlan {
        model_alias,
        tool_name,
        primary_input,
        output_field: return_output.clone(),
        output_contract: output_contract(module, return_output.as_deref()),
    })
}

fn push_prelude(output: &mut String, module: &AirModule) {
    output.push_str("// Generated by AIR OpenAI Agents JS semantic backend.\n");
    output.push_str("// This is semantic lowering: it projects AIR intent to an agent loop,\n");
    output.push_str("// not strict per-action state-machine execution.\n");
    output.push_str(&format!(
        "// Source agent: {} {}\n\n",
        module.agent.name, module.agent.version
    ));
    output.push_str("import fs from 'node:fs';\n");
    output.push_str("import OpenAI from 'openai';\n");
    output.push_str("import { Agent, run, setDefaultOpenAIClient, setOpenAIAPI, setTracingDisabled, tool } from '@openai/agents';\n");
    output.push_str("import { z } from 'zod';\n\n");
}

fn push_runtime_helpers(output: &mut String) {
    output.push_str(
r#"function readJson(path) {
  return JSON.parse(fs.readFileSync(path, 'utf8'));
}

function loadDotEnv(path = '.env') {
  if (!fs.existsSync(path)) return;
  const source = fs.readFileSync(path, 'utf8');
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

function parseArgs(argv) {
  const args = {};
  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input') args.input = argv[++index];
    else if (arg === '--model-config') args.modelConfig = argv[++index];
    else if (arg === '--tool-config') args.toolConfig = argv[++index];
    else if (arg === '--model-alias') args.modelAlias = argv[++index];
    else throw new Error(`unknown argument ${arg}`);
  }
  if (!args.input) throw new Error('--input is required');
  if (!args.modelConfig) throw new Error('--model-config is required');
  return args;
}

function configureOpenAICompatible(modelConfig, alias) {
  const model = modelConfig.models?.[alias];
  if (!model) throw new Error(`unknown model alias ${alias}`);
  const apiKeyEnv = model.api_key_env || 'OPENAI_API_KEY';
  const apiKey = process.env[apiKeyEnv];
  if (!apiKey) throw new Error(`environment variable ${apiKeyEnv} is not set`);
  const baseURL = modelBaseURL(model);

  setTracingDisabled(true);
  setOpenAIAPI('chat_completions');
  setDefaultOpenAIClient(new OpenAI({ apiKey, baseURL }));
  return model;
}

function modelBaseURL(model) {
  if (model.base_url_env && process.env[model.base_url_env]) return process.env[model.base_url_env];
  if (process.env.OPENAI_BASE_URL) return process.env.OPENAI_BASE_URL;
  if (model.base_url) return model.base_url;
  throw new Error('model must declare base_url or OPENAI_BASE_URL');
}

function modelName(model) {
  if (model.model_env && process.env[model.model_env]) return process.env[model.model_env];
  if (process.env.OPENAI_MODEL) return process.env.OPENAI_MODEL;
  if (model.model) return model.model;
  throw new Error('model must declare model or OPENAI_MODEL');
}

function makeLocalDocsSearchTool(toolConfig, airToolName) {
  if (!airToolName) return null;
  const configured = toolConfig?.tools?.[airToolName];
  if (!configured || configured.kind !== 'local_docs_search') {
    throw new Error(`tool config must define tools["${airToolName}"] as local_docs_search`);
  }
  const documents = configured.documents ?? [];
  const maxResults = configured.max_results ?? 3;
  return tool({
    name: toSdkToolName(airToolName),
    description: 'Search the local document knowledge base before answering.',
    parameters: z.object({ query: z.string() }),
    async execute({ query }) {
      const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
      const seen = new Set();
      const matches = documents
        .filter((doc) =>
          terms.some(
            (term) =>
              doc.title.toLowerCase().includes(term) ||
              doc.content.toLowerCase().includes(term),
          ),
        )
        .filter((doc) => {
          const key = docDedupeKey(doc);
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        })
        .slice(0, maxResults);
      console.error(`[openai-agents] ${toSdkToolName(airToolName)} -> ${matches.map((doc) => doc.id).join(',')}`);
      return { query, documents: matches };
    },
  });
}

function toSdkToolName(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function parseJsonish(value) {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  try {
    return JSON.parse(trimmed);
  } catch {
    // Continue below.
  }
  if (trimmed.startsWith('```')) {
    const lines = trimmed.split(/\r?\n/);
    if (lines[0].startsWith('```')) lines.shift();
    if (lines.at(-1)?.trim() === '```') lines.pop();
    try {
      return JSON.parse(lines.join('\n').trim());
    } catch {
      return { content: value };
    }
  }
  return { content: value };
}

function validateOutput(module, field, value) {
  const spec = module.state?.[field] ?? module.outputs?.[field] ?? module.inputs?.[field];
  if (!spec) return;
  const errors = validateValue(field, value, spec);
  if (errors.length) throw new Error(`AIR schema violation: ${errors.join('; ')}`);
}

function validateValue(path, value, spec) {
  if (typeof spec === 'string') return validatePrimitive(path, value, spec);
  if (!spec || typeof spec !== 'object') return [];
  const kind = spec.type;
  if (['string', 'integer', 'number', 'boolean', 'object'].includes(kind)) {
    return kind === 'object' ? validateObject(path, value, spec) : validatePrimitive(path, value, kind);
  }
  if (kind === 'array') return validateArray(path, value, spec);
  if (kind === 'enum') return (spec.enum ?? []).includes(value) ? [] : [`${path} expected enum [${(spec.enum ?? []).join(', ')}] got ${JSON.stringify(value)}`];
  return [];
}

function validatePrimitive(path, value, kind) {
  const valid =
    (kind === 'string' && typeof value === 'string') ||
    (kind === 'integer' && Number.isInteger(value)) ||
    (kind === 'number' && typeof value === 'number' && Number.isFinite(value)) ||
    (kind === 'boolean' && typeof value === 'boolean') ||
    (kind === 'object' && value !== null && typeof value === 'object' && !Array.isArray(value));
  return valid ? [] : [`${path} expected ${kind} got ${valueKind(value)}`];
}

function validateObject(path, value, spec) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return [`${path} expected object got ${valueKind(value)}`];
  }
  const errors = [];
  for (const required of spec.required ?? []) {
    if (!(required in value)) errors.push(`${path}.${required} missing required field`);
  }
  for (const [field, fieldSpec] of Object.entries(spec.properties ?? {})) {
    if (field in value) errors.push(...validateValue(`${path}.${field}`, value[field], fieldSpec));
  }
  if (spec.additional_properties === false) {
    for (const field of Object.keys(value)) {
      if (!(field in (spec.properties ?? {}))) errors.push(`${path}.${field} unexpected additional field`);
    }
  }
  return errors;
}

function validateArray(path, value, spec) {
  if (!Array.isArray(value)) return [`${path} expected array got ${valueKind(value)}`];
  const errors = [];
  if (spec.min_items != null && value.length < spec.min_items) {
    errors.push(`${path} expected at least ${spec.min_items} items got ${value.length}`);
  }
  if (spec.max_items != null && value.length > spec.max_items) {
    errors.push(`${path} expected at most ${spec.max_items} items got ${value.length}`);
  }
  if (!spec.items) return errors;
  return errors.concat(value.flatMap((item, index) => validateValue(`${path}[${index}]`, item, spec.items)));
}

function valueKind(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

"#,
    );
}

fn push_strict_js_runtime(output: &mut String) {
    output.push_str(
r#"function readJson(path) {
  return JSON.parse(fs.readFileSync(path, 'utf8'));
}

function loadDotEnv(path = '.env') {
  if (!fs.existsSync(path)) return;
  const source = fs.readFileSync(path, 'utf8');
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

function parseArgs(argv) {
  const args = {};
  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input') args.input = argv[++index];
    else if (arg === '--model-config') args.modelConfig = argv[++index];
    else if (arg === '--tool-config') args.toolConfig = argv[++index];
    else throw new Error(`unknown argument ${arg}`);
  }
  if (!args.input) throw new Error('--input is required');
  if (!args.modelConfig) throw new Error('--model-config is required');
  return args;
}

function inputToContent(value) {
  return typeof value === 'string' ? value : JSON.stringify(value);
}

function parseJsonish(value) {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  try {
    return JSON.parse(trimmed);
  } catch {
    // Continue below.
  }
  if (trimmed.startsWith('```')) {
    const lines = trimmed.split(/\r?\n/);
    if (lines[0].startsWith('```')) lines.shift();
    if (lines.at(-1)?.trim() === '```') lines.pop();
    try {
      return JSON.parse(lines.join('\n').trim());
    } catch {
      return { content: value };
    }
  }
  return { content: value };
}

async function callModel(modelConfigRoot, name, inputValue) {
  const model = modelConfigRoot.models?.[name];
  if (!model) throw new Error(`unknown model alias ${name}`);
  const apiKeyEnv = model.api_key_env || 'OPENAI_API_KEY';
  const apiKey = process.env[apiKeyEnv];
  if (!apiKey) throw new Error(`environment variable ${apiKeyEnv} is not set`);
  const client = new OpenAI({ apiKey, baseURL: modelBaseURL(model) });
  const messages = [];
  if (model.system_prompt) messages.push({ role: 'system', content: model.system_prompt });
  messages.push({ role: 'user', content: inputToContent(inputValue) });
  const resolvedModel = modelName(model);
  console.error(`[openai-js] call_model ${name} -> ${resolvedModel}`);
  const response = await client.chat.completions.create({
    model: resolvedModel,
    messages,
    temperature: model.temperature ?? 0,
  });
  return parseJsonish(response.choices[0]?.message?.content ?? '');
}

async function callTool(toolConfigRoot, name, inputValue) {
  const tool = toolConfigRoot.tools?.[name];
  if (!tool) throw new Error(`unknown configured tool ${name}`);
  console.error(`[openai-js] call_tool ${name}`);
  if (tool.kind === 'local_docs_search') return searchDocs(inputValue, tool.documents ?? [], tool.max_results ?? 3);
  throw new Error(`unsupported configured tool kind ${tool.kind}`);
}

function validateToolCapability(module, action, toolConfigRoot) {
  const toolName = action.tool;
  const toolSpec = (module.tools ?? []).find((tool) => tool.name === toolName);
  if (!toolSpec) {
    throw new Error(`tool ${toolName} is not declared by module ${module.agent?.name ?? '<unknown>'}`);
  }
  if (toolSpec.capability && !(module.requires?.capabilities ?? []).includes(toolSpec.capability)) {
    throw new Error(`tool ${toolName} requires capability ${toolSpec.capability}, but module ${module.agent?.name ?? '<unknown>'} does not declare it in requires.capabilities`);
  }
  const providerCapability = toolConfigRoot.tools?.[toolName]?.capability;
  if (providerCapability && providerCapability !== toolSpec.capability) {
    throw new Error(`tool ${toolName} provider capability ${providerCapability} does not match module-declared capability ${toolSpec.capability ?? '<none>'}`);
  }
}

function applyWriteScope(toolName, inputValue, writeScope) {
  if (!['file.write', 'file.edit', 'edit'].includes(toolName) || writeScope == null) {
    return inputValue;
  }
  let allowedPaths;
  if (typeof writeScope === 'string') {
    allowedPaths = writeScope.trim() ? [writeScope.trim()] : [];
  } else if (Array.isArray(writeScope)) {
    allowedPaths = writeScope.map((path) => {
      if (typeof path !== 'string') throw new Error('tool_batch_dispatch write_scope entries must be strings');
      return path.trim();
    }).filter(Boolean);
  } else {
    throw new Error('tool_batch_dispatch write_scope must be a string or array of strings');
  }
  if (allowedPaths.length === 0) return inputValue;
  if (!inputValue || typeof inputValue !== 'object' || Array.isArray(inputValue)) {
    throw new Error(`tool ${toolName} input must be an object`);
  }
  return { ...inputValue, allowed_paths: allowedPaths };
}

function enforceRepeatedToolPolicy(module, toolHistory, toolName, inputValue) {
  const limit = module.policy?.max_repeated_tool_calls;
  if (limit == null) {
    return;
  }
  let attempted = 1;
  for (let index = toolHistory.length - 1; index >= 0; index -= 1) {
    const record = toolHistory[index];
    if (record.tool === toolName && JSON.stringify(record.input) === JSON.stringify(inputValue)) {
      attempted += 1;
      continue;
    }
    break;
  }
  if (attempted > Number(limit)) {
    throw new Error(`policy.max_repeated_tool_calls exceeded for tool ${toolName}: limit=${limit} attempted=${attempted}`);
  }
  toolHistory.push({ tool: toolName, input: inputValue });
}

function validateApprovalCapabilities(module, approvalFor) {
  const required = module.policy?.require_approval ?? [];
  for (const capability of approvalFor ?? []) {
    if (!required.includes(capability)) {
      throw new Error(`approval action in module ${module.agent?.name ?? '<unknown>'} references capability ${capability}, but policy.require_approval does not require it`);
    }
  }
}

async function requestApproval(toolConfigRoot, module, action, localState) {
  const approvalFor = action.approval_for ?? [];
  validateApprovalCapabilities(module, approvalFor);
  const approvals = toolConfigRoot.approvals ?? {};
  const decisions = [];
  for (const capability of approvalFor) {
    const decision = approvals[capability];
    if (!decision) {
      throw new Error(`approval is not wired for capability ${capability}`);
    }
    if (decision.approved !== true) {
      throw new Error(`approval denied for capability ${capability}: ${decision.reason ?? 'approval provider denied the request'}`);
    }
    decisions.push({ capability, ...decision });
  }
  return {
    approved: true,
    approval_for: approvalFor,
    approver: decisions.find((decision) => decision.approver)?.approver,
    reason: decisions.find((decision) => decision.reason)?.reason,
    decisions,
    state: toolConfigRoot.include_approval_state === true ? localState : undefined,
  };
}

function searchDocs(inputValue, documents, maxResults) {
  const query = String(inputValue?.query ?? '').toLowerCase();
  const terms = query.split(/\s+/).filter(Boolean);
  const seen = new Set();
  const matches = documents
    .filter((doc) =>
      terms.some((term) =>
        String(doc.title ?? '').toLowerCase().includes(term) ||
        String(doc.content ?? '').toLowerCase().includes(term),
      ),
    )
    .filter((doc) => {
      const key = docDedupeKey(doc);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, maxResults)
    .map((doc) => ({
      id: doc.id,
      title: doc.title,
      content: doc.content,
    }));
  return { query: inputValue?.query ?? '', documents: matches };
}

function docDedupeKey(doc) {
  const content = String(doc.content ?? '').trim().toLowerCase();
  if (content) return `content:${content}`;
  const title = String(doc.title ?? '').trim().toLowerCase();
  if (title) return `title:${title}`;
  return `id:${String(doc.id ?? '').trim().toLowerCase()}`;
}

function getPath(state, path) {
  for (const prefix of ['input.', 'state.', 'output.', 'outputs.']) {
    if (path.startsWith(prefix)) {
      path = path.slice(prefix.length);
      break;
    }
  }
  path = normalizePath(path);
  let value = state;
  for (const segment of path.split('.')) {
    value = value[segment];
  }
  return value;
}

function normalizePath(path) {
  return path.replace(/\[(\d+)\]/g, '.$1');
}

function readPath(localState, outputs, path) {
  return getPath({ ...localState, ...outputs }, path);
}

function renderTemplate(localState, outputs, template) {
  return template.replace(/\{\{([^}]+)\}\}/g, (_, path) => String(readPath(localState, outputs, path.trim())));
}

function evalInput(localState, outputs, spec) {
  if (typeof spec === 'string') return readPath(localState, outputs, spec);
  if (spec && typeof spec === 'object' && spec.fields) {
    return Object.fromEntries(Object.entries(spec.fields).map(([alias, field]) => [alias, readPath(localState, outputs, field)]));
  }
  return evalExpr(localState, outputs, spec);
}

function evalExpr(localState, outputs, expr) {
  if (!expr || typeof expr !== 'object') return expr;
  if ('ref' in expr) return readPath(localState, outputs, expr.ref);
  if ('path' in expr) return readPath(localState, outputs, expr.path);
  if ('literal' in expr) return expr.literal;
  if ('object' in expr) return Object.fromEntries(Object.entries(expr.object).map(([key, value]) => [key, evalExpr(localState, outputs, value)]));
  if ('array' in expr) return expr.array.map((value) => evalExpr(localState, outputs, value));
  if ('template' in expr) return renderTemplate(localState, outputs, expr.template);
  if ('truncate' in expr) {
    const value = evalExpr(localState, outputs, expr.truncate);
    const raw = typeof value === 'string' ? value : JSON.stringify(value);
    return raw.slice(0, expr.max_chars);
  }
  return expr;
}

function looksLikeExpr(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const keys = Object.keys(value);
  return keys.length === 1 && ['ref', 'path', 'literal', 'object', 'array', 'template', 'truncate'].includes(keys[0]);
}

function resolveSetValue(localState, outputs, value) {
  return looksLikeExpr(value) ? evalExpr(localState, outputs, value) : value;
}

function parseConditionLiteral(raw) {
  raw = raw.trim();
  if (!raw) throw new Error('unsupported empty condition literal');
  if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
    return raw.slice(1, -1);
  }
  return JSON.parse(raw);
}

function conditionClauseMatches(localState, outputs, clause) {
  let left;
  let right;
  let expectedEqual;
  if (clause.includes('==')) {
    [left, right] = clause.split('==');
    expectedEqual = true;
  } else if (clause.includes('!=')) {
    [left, right] = clause.split('!=');
    expectedEqual = false;
  } else {
    throw new Error(`unsupported condition clause ${clause}`);
  }
  const actual = readPath(localState, outputs, left.trim());
  const expected = parseConditionLiteral(right);
  return (JSON.stringify(actual) === JSON.stringify(expected)) === expectedEqual;
}

function conditionMatches(localState, outputs, condition) {
  return condition
    .split('||')
    .some((group) => group.split('&&').every((clause) => conditionClauseMatches(localState, outputs, clause.trim())));
}

function validateOutput(module, field, value) {
  const spec = module.state?.[field] ?? module.outputs?.[field] ?? module.inputs?.[field];
  if (!spec) return;
  const errors = validateValue(field, value, spec);
  if (errors.length) throw new Error(`AIR schema violation: ${errors.join('; ')}`);
}

function validateValue(path, value, spec) {
  if (typeof spec === 'string') return validatePrimitive(path, value, spec);
  if (!spec || typeof spec !== 'object') return [];
  const kind = spec.type;
  if (['string', 'integer', 'number', 'boolean', 'object'].includes(kind)) {
    return kind === 'object' ? validateObject(path, value, spec) : validatePrimitive(path, value, kind);
  }
  if (kind === 'array') return validateArray(path, value, spec);
  if (kind === 'enum') return (spec.enum ?? []).includes(value) ? [] : [`${path} expected enum [${(spec.enum ?? []).join(', ')}] got ${JSON.stringify(value)}`];
  return [];
}

function validatePrimitive(path, value, kind) {
  const valid =
    (kind === 'string' && typeof value === 'string') ||
    (kind === 'integer' && Number.isInteger(value)) ||
    (kind === 'number' && typeof value === 'number' && Number.isFinite(value)) ||
    (kind === 'boolean' && typeof value === 'boolean') ||
    (kind === 'object' && value !== null && typeof value === 'object' && !Array.isArray(value));
  return valid ? [] : [`${path} expected ${kind} got ${valueKind(value)}`];
}

function validateObject(path, value, spec) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return [`${path} expected object got ${valueKind(value)}`];
  }
  const errors = [];
  for (const required of spec.required ?? []) {
    if (!(required in value)) errors.push(`${path}.${required} missing required field`);
  }
  for (const [field, fieldSpec] of Object.entries(spec.properties ?? {})) {
    if (field in value) errors.push(...validateValue(`${path}.${field}`, value[field], fieldSpec));
  }
  if (spec.additional_properties === false) {
    for (const field of Object.keys(value)) {
      if (!(field in (spec.properties ?? {}))) errors.push(`${path}.${field} unexpected additional field`);
    }
  }
  return errors;
}

function validateArray(path, value, spec) {
  if (!Array.isArray(value)) return [`${path} expected array got ${valueKind(value)}`];
  const errors = [];
  if (spec.min_items != null && value.length < spec.min_items) {
    errors.push(`${path} expected at least ${spec.min_items} items got ${value.length}`);
  }
  if (spec.max_items != null && value.length > spec.max_items) {
    errors.push(`${path} expected at most ${spec.max_items} items got ${value.length}`);
  }
  if (!spec.items) return errors;
  return errors.concat(value.flatMap((item, index) => validateValue(`${path}[${index}]`, item, spec.items)));
}

function valueKind(value) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

function traceEnabled() {
  return ['1', 'true', 'json', 'debug'].includes(String(process.env.AIR_TRACE ?? '').toLowerCase());
}

function emitTrace({ agent, step, rule, action, status, input, output, meta, error }) {
  if (!traceEnabled()) return;
  const event = { agent, step, rule, action, status };
  if (input !== undefined) event.input = input;
  if (output !== undefined) event.output = output;
  if (meta !== undefined) event.meta = meta;
  if (error !== undefined) event.error = error;
  process.stderr.write(`${JSON.stringify(event)}\n`);
}

function actionMeta(action, { elapsedMs, attempt, maxAttempts, willRetry } = {}) {
  const meta = {};
  if (action.model != null) meta.model = action.model;
  if (action.tool != null) meta.tool = action.tool;
  if (action.requested_tool != null) meta.requested_tool = action.requested_tool;
  if (action.output != null) meta.output = action.output;
  if (action.timeout_seconds != null) meta.timeout_seconds = action.timeout_seconds;
  if (elapsedMs != null) meta.elapsed_ms = elapsedMs;
  if (attempt != null) meta.attempt = attempt;
  if (maxAttempts != null) meta.max_attempts = maxAttempts;
  if (willRetry != null) meta.will_retry = willRetry;
  return meta;
}

function normalizeModelSelectedToolName(module, toolName) {
  if ((module.tools ?? []).some((tool) => tool.name === toolName)) {
    return { toolName, requestedTool: undefined };
  }
  const normalized = toolName.toLowerCase();
  if (normalized !== toolName && (module.tools ?? []).some((tool) => tool.name === normalized)) {
    return { toolName: normalized, requestedTool: toolName };
  }
  return { toolName, requestedTool: undefined };
}

function checkModuleTimeout(module, startedAt) {
  const limit = module.policy?.timeout_seconds;
  if (limit == null) return;
  const elapsedMs = Date.now() - startedAt;
  if (elapsedMs >= Number(limit) * 1000) {
    throw new Error(`policy.timeout_seconds exceeded: limit=${limit} elapsed_ms=${elapsedMs}`);
  }
}

function checkActionTimeout(kind, timeoutSeconds, startedAt) {
  const elapsedMs = Date.now() - startedAt;
  if (elapsedMs >= Number(timeoutSeconds) * 1000) {
    throw new Error(`${kind} action exceeded timeout_seconds=${timeoutSeconds} elapsed_ms=${elapsedMs}`);
  }
}

function retryInput(inputValue, attempt, previousError, module, action) {
  const reason = isTokenLimitError(previousError) ? 'token_limit' : 'previous_error';
  const maxInputChars = reason === 'token_limit' ? tokenLimitMaxInputChars(action, attempt) : null;
  const nextInput = maxInputChars == null ? inputValue : compactJsonValue(inputValue, maxInputChars);
  const retryContext = {
    attempt,
    previous_error: previousError,
    reason,
    instruction: 'The previous response failed AIR runtime schema validation. Return only a corrected JSON object matching required_output_schema exactly.',
  };
  if (maxInputChars != null) {
    retryContext.max_input_chars = maxInputChars;
    retryContext.compaction = 'input was truncated after a provider token/context limit error';
  }
  const schema = module.state?.[action.output] ?? module.outputs?.[action.output];
  if (schema) retryContext.required_output_schema = schema;
  if (nextInput !== null && typeof nextInput === 'object' && !Array.isArray(nextInput)) {
    return { ...nextInput, _air_retry: retryContext };
  }
  return { input: nextInput, _air_retry: retryContext };
}

function isTokenLimitError(message) {
  const lowered = String(message ?? '').toLowerCase();
  return [
    'context_length_exceeded',
    'context length',
    'maximum context',
    'max context',
    'token limit',
    'too many tokens',
    'input is too long',
  ].some((needle) => lowered.includes(needle));
}

function tokenLimitMaxInputChars(action, attempt) {
  const values = action.retry?.on_provider_error?.token_limit?.max_input_chars ?? [];
  if (!values.length) return null;
  const index = Math.max(0, attempt - 2);
  return Number(values[index] ?? values.at(-1));
}

function compactJsonValue(value, maxChars) {
  const remaining = { chars: Math.max(0, Number(maxChars)) };
  return compactJsonValueWithBudget(value, remaining);
}

function compactJsonValueWithBudget(value, remaining) {
  if (typeof value === 'string') {
    if (remaining.chars === 0) return '';
    if (value.length <= remaining.chars) {
      remaining.chars -= value.length;
      return value;
    }
    const truncated = value.slice(0, remaining.chars);
    remaining.chars = 0;
    return `${truncated}\n[air:truncated]`;
  }
  if (Array.isArray(value)) return value.map((item) => compactJsonValueWithBudget(item, remaining));
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, compactJsonValueWithBudget(item, remaining)]));
  }
  return value;
}

function runtimeContext(step, maxSteps) {
  const remainingSteps = Math.max(0, Number(maxSteps) - Number(step));
  return {
    step: Number(step),
    step_number: Number(step) + 1,
    max_steps: Number(maxSteps),
    remaining_steps: remainingSteps,
    is_last_step: remainingSteps <= 1,
    is_last_action_step: remainingSteps <= 2,
  };
}

async function runModule(modelConfig, toolConfig, moduleId, moduleInputs) {
  const module = MODULES[moduleId];
  const workflow = module.workflow;
  const localState = { ...moduleInputs, phase: workflow.initial };
  const outputs = {};
  const startedAt = Date.now();
  let modelCalls = 0;
  let toolCalls = 0;
  const toolHistory = [];

  for (let step = 0; step < workflow.max_steps; step += 1) {
    localState._air = runtimeContext(step, workflow.max_steps);
    const currentPhase = localState.phase;
    const rule = workflow.rules.find((candidate) => conditionMatches(localState, outputs, candidate.when));
    if (!rule) throw new Error(`no rule matched module=${moduleId} phase=${currentPhase}`);
    const ruleId = rule.id ?? '';
    for (const action of rule.actions ?? []) {
      if (action.kind === 'set') {
        const resolvedValues = {};
        for (const [key, value] of Object.entries(action.values ?? {})) {
          const resolved = resolveSetValue(localState, outputs, value);
          validateOutput(module, key, resolved);
          localState[key] = resolved;
          resolvedValues[key] = resolved;
        }
        emitTrace({ agent: moduleId, step, rule: ruleId, action: 'set', status: 'ok', output: resolvedValues });
      } else if (action.kind === 'append') {
        const inputValue = evalInput(localState, outputs, action.value);
        const existing = Array.isArray(localState[action.target]) ? [...localState[action.target]] : [];
        existing.push(inputValue);
        try {
          validateOutput(module, action.target, existing);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'append', status: 'error', input: inputValue, output: existing, error: String(error?.message ?? error) });
          throw error;
        }
        localState[action.target] = existing;
        emitTrace({ agent: moduleId, step, rule: ruleId, action: 'append', status: 'ok', input: inputValue, output: existing, meta: { target: action.target } });
      } else if (action.kind === 'model_call') {
        const inputValue = evalInput(localState, outputs, action.input);
        const maxAttempts = Math.max(1, Number(action.retry?.max_attempts ?? 1));
        let previousError = null;
        for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
          const attemptInput = previousError ? retryInput(inputValue, attempt, previousError, module, action) : inputValue;
          const limit = module.policy?.max_model_calls;
          if (limit != null && modelCalls + 1 > Number(limit)) {
            const error = new Error(`policy.max_model_calls exceeded: limit=${limit} attempted=${modelCalls + 1}`);
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'model_call', status: 'error', input: attemptInput, meta: actionMeta(action, { attempt, maxAttempts, willRetry: false }), error: error.message });
            throw error;
          }
          modelCalls += 1;
          const actionStartedAt = Date.now();
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'model_call_start', status: 'ok', input: attemptInput, meta: actionMeta(action, { attempt, maxAttempts }) });
          let resultValue;
          try {
            resultValue = await callModel(modelConfig, action.model, attemptInput);
            checkActionTimeout('model_call', action.timeout_seconds, actionStartedAt);
            validateOutput(module, action.output, resultValue);
            localState[action.output] = resultValue;
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'model_call', status: 'ok', input: attemptInput, output: resultValue, meta: actionMeta(action, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: false }) });
            break;
          } catch (error) {
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'model_call', status: 'error', input: attemptInput, output: resultValue, meta: actionMeta(action, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: attempt !== maxAttempts }), error: String(error?.message ?? error) });
            if (attempt === maxAttempts) throw error;
            previousError = String(error?.message ?? error);
          }
        }
      } else if (action.kind === 'tool_call') {
        try {
          validateToolCapability(module, action, toolConfig);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call', status: 'error', meta: { tool: action.tool }, error: String(error?.message ?? error) });
          throw error;
        }
        const inputValue = evalInput(localState, outputs, action.input);
        try {
          enforceRepeatedToolPolicy(module, toolHistory, action.tool, inputValue);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call', status: 'error', input: inputValue, meta: { tool: action.tool }, error: String(error?.message ?? error) });
          throw error;
        }
        const maxAttempts = Math.max(1, Number(action.retry?.max_attempts ?? 1));
        for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
          const limit = module.policy?.max_tool_calls;
          if (limit != null && toolCalls + 1 > Number(limit)) {
            const error = new Error(`policy.max_tool_calls exceeded: limit=${limit} attempted=${toolCalls + 1}`);
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call', status: 'error', input: inputValue, meta: actionMeta(action, { attempt, maxAttempts, willRetry: false }), error: error.message });
            throw error;
          }
          toolCalls += 1;
          const actionStartedAt = Date.now();
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call_start', status: 'ok', input: inputValue, meta: actionMeta(action, { attempt, maxAttempts }) });
          let resultValue;
          try {
            resultValue = await callTool(toolConfig, action.tool, inputValue);
            checkActionTimeout('tool_call', action.timeout_seconds, actionStartedAt);
            validateOutput(module, action.output, resultValue);
            localState[action.output] = resultValue;
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call', status: 'ok', input: inputValue, output: resultValue, meta: actionMeta(action, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: false }) });
            break;
          } catch (error) {
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_call', status: 'error', input: inputValue, output: resultValue, meta: actionMeta(action, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: attempt !== maxAttempts }), error: String(error?.message ?? error) });
            if (attempt === maxAttempts) throw error;
          }
        }
      } else if (action.kind === 'tool_dispatch') {
        const dispatchValue = evalInput(localState, outputs, action.input);
        if (!dispatchValue || typeof dispatchValue !== 'object' || Array.isArray(dispatchValue) || typeof dispatchValue.tool !== 'string') {
          throw new Error('tool_dispatch input.tool must be a string');
        }
        const normalized = normalizeModelSelectedToolName(module, dispatchValue.tool);
        const dispatchedAction = { ...action, tool: normalized.toolName };
        if (normalized.requestedTool != null) dispatchedAction.requested_tool = normalized.requestedTool;
        try {
          validateToolCapability(module, dispatchedAction, toolConfig);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch', status: 'error', meta: actionMeta(dispatchedAction), error: String(error?.message ?? error) });
          throw error;
        }
        const inputValue = dispatchValue.input ?? {};
        try {
          enforceRepeatedToolPolicy(module, toolHistory, normalized.toolName, inputValue);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch', status: 'error', input: inputValue, meta: actionMeta(dispatchedAction), error: String(error?.message ?? error) });
          throw error;
        }
        const maxAttempts = Math.max(1, Number(action.retry?.max_attempts ?? 1));
        for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
          const limit = module.policy?.max_tool_calls;
          if (limit != null && toolCalls + 1 > Number(limit)) {
            const error = new Error(`policy.max_tool_calls exceeded: limit=${limit} attempted=${toolCalls + 1}`);
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch', status: 'error', input: inputValue, meta: actionMeta(dispatchedAction, { attempt, maxAttempts, willRetry: false }), error: error.message });
            throw error;
          }
          toolCalls += 1;
          const actionStartedAt = Date.now();
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch_start', status: 'ok', input: inputValue, meta: actionMeta(dispatchedAction, { attempt, maxAttempts }) });
          let resultValue;
          try {
            resultValue = await callTool(toolConfig, normalized.toolName, inputValue);
            checkActionTimeout('tool_dispatch', action.timeout_seconds, actionStartedAt);
            validateOutput(module, action.output, resultValue);
            localState[action.output] = resultValue;
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch', status: 'ok', input: inputValue, output: resultValue, meta: actionMeta(dispatchedAction, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: false }) });
            break;
          } catch (error) {
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_dispatch', status: 'error', input: inputValue, output: resultValue, meta: actionMeta(dispatchedAction, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: attempt !== maxAttempts }), error: String(error?.message ?? error) });
            if (attempt === maxAttempts) throw error;
          }
        }
      } else if (action.kind === 'tool_batch_dispatch') {
        const batchValue = evalInput(localState, outputs, action.input);
        const writeScope = action.write_scope == null ? null : evalInput(localState, outputs, action.write_scope);
        if (!Array.isArray(batchValue)) {
          throw new Error('tool_batch_dispatch input must be an array');
        }
        const maxCalls = Number(action.max_calls ?? 0);
        if (batchValue.length > maxCalls) {
          const error = new Error(`tool_batch_dispatch max_calls exceeded: limit=${maxCalls} attempted=${batchValue.length}`);
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch', status: 'error', input: batchValue, meta: { max_calls: maxCalls, attempted: batchValue.length }, error: error.message });
          throw error;
        }
        const batchOutputs = [];
        const maxAttempts = Math.max(1, Number(action.retry?.max_attempts ?? 1));
        const observeErrors = action.on_error === 'observe';
        for (let index = 0; index < batchValue.length; index += 1) {
          const dispatchValue = batchValue[index];
          if (!dispatchValue || typeof dispatchValue !== 'object' || Array.isArray(dispatchValue) || typeof dispatchValue.tool !== 'string') {
            const error = new Error(`tool_batch_dispatch input[${index}].tool must be a string`);
            if (observeErrors) {
              batchOutputs.push({ tool: '<invalid>', input: {}, status: 'error', error: error.message, output: { status: 'error', error: error.message, requested: dispatchValue } });
              continue;
            }
            throw error;
          }
          const normalized = normalizeModelSelectedToolName(module, dispatchValue.tool);
          const dispatchedAction = { ...action, tool: normalized.toolName };
          if (normalized.requestedTool != null) dispatchedAction.requested_tool = normalized.requestedTool;
          const inputValue = applyWriteScope(normalized.toolName, dispatchValue.input ?? {}, writeScope);
          try {
            validateToolCapability(module, dispatchedAction, toolConfig);
          } catch (error) {
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item', status: 'error', meta: { ...actionMeta(dispatchedAction), index }, error: String(error?.message ?? error) });
            if (observeErrors && String(error?.message ?? error).includes('is not declared by module')) {
              const message = String(error?.message ?? error);
              batchOutputs.push({ tool: normalized.toolName, input: inputValue, status: 'error', error: message, output: { status: 'error', error: message } });
              continue;
            }
            throw error;
          }
          try {
            enforceRepeatedToolPolicy(module, toolHistory, normalized.toolName, inputValue);
          } catch (error) {
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item', status: 'error', input: inputValue, meta: { ...actionMeta(dispatchedAction), index }, error: String(error?.message ?? error) });
            if (observeErrors) {
              const message = String(error?.message ?? error);
              batchOutputs.push({ tool: normalized.toolName, input: inputValue, status: 'error', error: message, output: { status: 'error', error: message } });
              continue;
            }
            throw error;
          }
          for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
            const limit = module.policy?.max_tool_calls;
            if (limit != null && toolCalls + 1 > Number(limit)) {
              const error = new Error(`policy.max_tool_calls exceeded: limit=${limit} attempted=${toolCalls + 1}`);
              emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item', status: 'error', input: inputValue, meta: { ...actionMeta(dispatchedAction, { attempt, maxAttempts, willRetry: false }), index }, error: error.message });
              throw error;
            }
            toolCalls += 1;
            const actionStartedAt = Date.now();
            emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item_start', status: 'ok', input: inputValue, meta: { ...actionMeta(dispatchedAction, { attempt, maxAttempts }), index } });
            let resultValue;
            try {
              resultValue = await callTool(toolConfig, normalized.toolName, inputValue);
              checkActionTimeout('tool_batch_dispatch_item', action.timeout_seconds, actionStartedAt);
              emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item', status: 'ok', input: inputValue, output: resultValue, meta: { ...actionMeta(dispatchedAction, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: false }), index } });
              batchOutputs.push({ tool: normalized.toolName, input: inputValue, status: 'ok', output: resultValue });
              break;
            } catch (error) {
              emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch_item', status: 'error', input: inputValue, output: resultValue, meta: { ...actionMeta(dispatchedAction, { elapsedMs: Date.now() - actionStartedAt, attempt, maxAttempts, willRetry: attempt !== maxAttempts }), index }, error: String(error?.message ?? error) });
              if (attempt === maxAttempts) {
                if (observeErrors) {
                  const message = String(error?.message ?? error);
                  batchOutputs.push({ tool: normalized.toolName, input: inputValue, status: 'error', error: message, output: { status: 'error', error: message } });
                  break;
                }
                throw error;
              }
            }
          }
        }
        try {
          validateOutput(module, action.output, batchOutputs);
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch', status: 'error', input: batchValue, output: batchOutputs, meta: { count: batchOutputs.length, max_calls: maxCalls }, error: String(error?.message ?? error) });
          throw error;
        }
        localState[action.output] = batchOutputs;
        emitTrace({ agent: moduleId, step, rule: ruleId, action: 'tool_batch_dispatch', status: 'ok', input: batchValue, output: batchOutputs, meta: { count: batchOutputs.length, max_calls: maxCalls, error_count: batchOutputs.filter((item) => item?.status === 'error').length } });
      } else if (action.kind === 'approval') {
        try {
          const decision = await requestApproval(toolConfig, module, action, localState);
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'approval', status: 'ok', output: decision, meta: { approval_for: action.approval_for ?? [], approved: true, approver: decision.approver, reason: decision.reason } });
        } catch (error) {
          emitTrace({ agent: moduleId, step, rule: ruleId, action: 'approval', status: 'error', meta: { approval_for: action.approval_for ?? [] }, error: String(error?.message ?? error) });
          throw error;
        }
      } else if (action.kind === 'return') {
        outputs[action.output] = readPath(localState, outputs, action.output);
        emitTrace({ agent: moduleId, step, rule: ruleId, action: 'return', status: 'ok', output: outputs[action.output], meta: { output: action.output } });
      } else {
        throw new Error(`unsupported action kind ${action.kind}`);
      }
      checkModuleTimeout(module, startedAt);
    }
    if ((workflow.terminal ?? []).includes(localState.phase)) {
      const terminal = workflow.rules.find((candidate) => conditionMatches(localState, outputs, candidate.when));
      if (terminal && terminal !== rule) {
        const terminalRuleId = terminal.id ?? '';
        for (const action of terminal.actions ?? []) {
          if (action.kind === 'return') {
            outputs[action.output] = readPath(localState, outputs, action.output);
            emitTrace({ agent: moduleId, step, rule: terminalRuleId, action: 'return', status: 'ok', output: outputs[action.output], meta: { output: action.output } });
          }
        }
      }
      return outputs;
    }
  }
  throw new Error(`module ${moduleId} exceeded max_steps=${workflow.max_steps}`);
}

function assignInput(inputs, field, value) {
  if (field.endsWith('[]')) {
    field = field.slice(0, -2);
    if (!Array.isArray(inputs[field])) inputs[field] = [];
    inputs[field].push(value);
  } else {
    inputs[field] = value;
  }
}

function endpointValue(state, endpoint) {
  if (endpoint.startsWith('$input.')) return state[endpoint.slice('$input.'.length)];
  const [moduleId, ...fieldPath] = endpoint.split('.');
  return getPath(state[moduleId], fieldPath.join('.'));
}

function emptyLinkValue(value) {
  return value == null
    || value === ''
    || (Array.isArray(value) && value.length === 0)
    || (typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 0);
}

function linkExprValue(state, expr) {
  if (Object.prototype.hasOwnProperty.call(expr, 'from')) return endpointValue(state, expr.from);
  if (Object.prototype.hasOwnProperty.call(expr, 'literal')) return expr.literal;
  if (Object.prototype.hasOwnProperty.call(expr, 'object')) {
    const out = {};
    for (const [key, value] of Object.entries(expr.object)) out[key] = linkExprValue(state, value);
    return out;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'array')) return expr.array.map((value) => linkExprValue(state, value));
  if (Object.prototype.hasOwnProperty.call(expr, 'count')) {
    const value = linkExprValue(state, expr.count);
    if (!Array.isArray(value)) throw new Error('count expression requires an array input');
    return value.length;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'coalesce')) {
    let emptyFallback = null;
    for (const candidate of expr.coalesce) {
      try {
        const value = linkExprValue(state, candidate);
        if (!emptyLinkValue(value)) return value;
        emptyFallback = value;
      } catch (error) {
        continue;
      }
    }
    return emptyFallback;
  }
  throw new Error(`unsupported AIR link expression ${JSON.stringify(expr)}`);
}

function dynamicLinkExprValue(state, expr, item) {
  if (Object.prototype.hasOwnProperty.call(expr, 'from')) {
    return expr.from === '$item' || expr.from.startsWith('$item.')
      ? itemValue(item, expr.from)
      : endpointValue(state, expr.from);
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'literal')) return expr.literal;
  if (Object.prototype.hasOwnProperty.call(expr, 'object')) {
    const out = {};
    for (const [key, value] of Object.entries(expr.object)) out[key] = dynamicLinkExprValue(state, value, item);
    return out;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'array')) return expr.array.map((value) => dynamicLinkExprValue(state, value, item));
  if (Object.prototype.hasOwnProperty.call(expr, 'count')) {
    const value = dynamicLinkExprValue(state, expr.count, item);
    if (!Array.isArray(value)) throw new Error('count expression requires an array input');
    return value.length;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'coalesce')) {
    let emptyFallback = null;
    for (const candidate of expr.coalesce) {
      try {
        const value = dynamicLinkExprValue(state, candidate, item);
        if (!emptyLinkValue(value)) return value;
        emptyFallback = value;
      } catch (error) {
        continue;
      }
    }
    return emptyFallback;
  }
  throw new Error(`unsupported AIR link expression ${JSON.stringify(expr)}`);
}

function eachLinkExprValue(state, expr, nodeId) {
  if (Object.prototype.hasOwnProperty.call(expr, 'from')) {
    if (expr.from === '$each') return state[nodeId];
    if (expr.from.startsWith('$each.')) return getPath(state[nodeId], expr.from.slice('$each.'.length));
    return endpointValue(state, expr.from);
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'literal')) return expr.literal;
  if (Object.prototype.hasOwnProperty.call(expr, 'object')) {
    const out = {};
    for (const [key, value] of Object.entries(expr.object)) out[key] = eachLinkExprValue(state, value, nodeId);
    return out;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'array')) return expr.array.map((value) => eachLinkExprValue(state, value, nodeId));
  if (Object.prototype.hasOwnProperty.call(expr, 'count')) {
    const value = eachLinkExprValue(state, expr.count, nodeId);
    if (!Array.isArray(value)) throw new Error('count expression requires an array input');
    return value.length;
  }
  if (Object.prototype.hasOwnProperty.call(expr, 'coalesce')) {
    let emptyFallback = null;
    for (const candidate of expr.coalesce) {
      try {
        const value = eachLinkExprValue(state, candidate, nodeId);
        if (!emptyLinkValue(value)) return value;
        emptyFallback = value;
      } catch (error) {
        continue;
      }
    }
    return emptyFallback;
  }
  throw new Error(`unsupported AIR link expression ${JSON.stringify(expr)}`);
}

function moduleInputs(state, moduleId) {
  const inputs = {};
  for (const connection of RUN_PLAN.connect ?? []) {
    const [toModule, ...toPath] = connection.to.split('.');
    if (toModule !== moduleId) continue;
    const value = connection.value != null
      ? linkExprValue(state, connection.value)
      : endpointValue(state, connection.from);
    assignInput(inputs, toPath.join('.'), value);
  }
  for (const fanout of RUN_PLAN.dynamic?.fanouts ?? []) {
    for (const node of state.__air_dynamic_materialized?.[fanout.id] ?? []) {
      for (const connection of fanout.fan_in ?? []) {
        const [toModule, ...toPath] = connection.to.split('.');
        if (toModule !== moduleId) continue;
        if (connection.value != null) {
          assignInput(inputs, toPath.join('.'), eachLinkExprValue(state, connection.value, node.id));
          continue;
        }
        if (!connection.from.startsWith('$each.')) throw new Error(`dynamic fan_in source ${connection.from} must start with $each.`);
        assignInput(inputs, toPath.join('.'), getPath(state[node.id], connection.from.slice('$each.'.length)));
      }
    }
  }
  return inputs;
}

function dynamicItemId(fanout, index) {
  return `${fanout.id_prefix}_${index + 1}`;
}

function dynamicChildItemId(fanout, parentIndex, index) {
  return `${fanout.id_prefix}_${parentIndex + 1}_${index + 1}`;
}

function itemValue(item, source) {
  if (source === '$item') return item;
  if (source.startsWith('$item.')) return getPath(item, source.slice('$item.'.length));
  throw new Error(`dynamic input source ${source} must be $item, $item.<path>, or an endpoint`);
}

function dynamicInputs(state, fanout, item) {
  const inputs = {};
  for (const connection of fanout.input ?? []) {
    if (!connection.to.startsWith('$each.')) throw new Error(`dynamic input target ${connection.to} must start with $each.`);
    const field = connection.to.slice('$each.'.length);
    const value = connection.value != null
      ? dynamicLinkExprValue(state, connection.value, item)
      : connection.from === '$item' || connection.from.startsWith('$item.')
      ? itemValue(item, connection.from)
      : endpointValue(state, connection.from);
    assignInput(inputs, field, value);
  }
  return inputs;
}

function enforceDynamicBounds(fanout, items) {
  if (!Array.isArray(items)) throw new Error(`fanout ${fanout.id} source ${fanout.source} must evaluate to an array`);
  if (fanout.min_items != null && items.length < fanout.min_items) {
    throw new Error(`fanout ${fanout.id} expected at least ${fanout.min_items} items, got ${items.length}`);
  }
  if (items.length > fanout.max_items) {
    throw new Error(`fanout ${fanout.id} expected at most ${fanout.max_items} items, got ${items.length}`);
  }
}

async function runDynamicFanout(state, modelConfig, toolConfig, fanout) {
  if (!state.__air_dynamic_materialized) state.__air_dynamic_materialized = {};
  if (state.__air_dynamic_materialized[fanout.id]) return;
  const created = [];
  if (fanout.source.startsWith('$parent.')) {
    const parentNodes = state.__air_dynamic_materialized[fanout.after] ?? [];
    for (const [parentIndex, parentNode] of parentNodes.entries()) {
      const source = `${parentNode.id}.${fanout.source.slice('$parent.'.length)}`;
      const items = endpointValue(state, source);
      enforceDynamicBounds(fanout, items);
      for (let index = 0; index < items.length; index += 1) {
        created.push({ id: dynamicChildItemId(fanout, parentIndex, index), source, item_index: index });
      }
    }
  } else {
    const items = endpointValue(state, fanout.source);
    enforceDynamicBounds(fanout, items);
    for (let index = 0; index < items.length; index += 1) {
      created.push({ id: dynamicItemId(fanout, index), source: fanout.source, item_index: index });
    }
  }
  state.__air_dynamic_materialized[fanout.id] = created;
  emitTrace({
    agent: '$planner',
    step: 0,
    rule: fanout.id,
    action: 'dynamic_fanout',
    status: 'ok',
    input: { source: fanout.source, after: fanout.after },
    output: created,
    meta: { module: fanout.module, count: created.length, max_items: fanout.max_items },
  });
  for (const node of created) {
    const items = endpointValue(state, node.source);
    const item = items[node.item_index];
    state[node.id] = await runModule(modelConfig, toolConfig, fanout.module, dynamicInputs(state, fanout, item));
  }
  await runDynamicAfter(state, modelConfig, toolConfig, fanout.id);
}

async function runDynamicAfter(state, modelConfig, toolConfig, after) {
  for (const fanout of RUN_PLAN.dynamic?.fanouts ?? []) {
    if (fanout.after === after) await runDynamicFanout(state, modelConfig, toolConfig, fanout);
  }
}

function topologicalOrder() {
  const ids = RUN_PLAN.nodes.map((node) => node.id);
  const indegree = Object.fromEntries(ids.map((id) => [id, 0]));
  const outgoing = Object.fromEntries(ids.map((id) => [id, []]));
  for (const edge of RUN_PLAN.edges ?? []) {
    indegree[edge.to] += 1;
    outgoing[edge.from].push(edge.to);
  }
  const ready = ids.filter((id) => indegree[id] === 0);
  const order = [];
  while (ready.length) {
    const id = ready.shift();
    order.push(id);
    for (const next of outgoing[id]) {
      indegree[next] -= 1;
      if (indegree[next] === 0) ready.push(next);
    }
  }
  if (order.length !== ids.length) throw new Error('cycle detected in RunPlan');
  return order;
}

function validateRunPlanCapabilities() {
  const allowed = new Set(RUN_PLAN.requires?.capabilities ?? []);
  for (const node of RUN_PLAN.nodes ?? []) {
    const module = MODULES[node.id] ?? {};
    for (const capability of module.requires?.capabilities ?? []) {
      if (!allowed.has(capability)) {
        throw new Error(`RunPlan uses node ${node.id} requiring capability ${capability}, but it is missing from RUN_PLAN.requires.capabilities`);
      }
    }
  }
}

async function main() {
  loadDotEnv();
  const args = parseArgs(process.argv);
  const state = readJson(args.input);
  const modelConfig = readJson(args.modelConfig);
  const toolConfig = args.toolConfig ? readJson(args.toolConfig) : { tools: {} };
  validateRunPlanCapabilities();
  for (const moduleId of topologicalOrder()) {
    state[moduleId] = await runModule(modelConfig, toolConfig, moduleId, moduleInputs(state, moduleId));
    await runDynamicAfter(state, modelConfig, toolConfig, moduleId);
  }
  const outputs = {};
  for (const [name, endpoint] of Object.entries(RUN_PLAN.outputs ?? {})) {
    const [moduleId, ...fieldPath] = endpoint.split('.');
    outputs[name] = getPath(state[moduleId], fieldPath.join('.'));
  }
  console.log(JSON.stringify(outputs, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
"#,
    );
}

fn push_main(output: &mut String, module: &AirModule, plan: &SemanticPlan) {
    let tool_name_literal = js_optional_string(plan.tool_name.as_deref());
    let sdk_tool_name = plan
        .tool_name
        .as_deref()
        .map(to_sdk_tool_name)
        .unwrap_or_default();
    let primary_input = js_string(&plan.primary_input);
    let output_field = js_optional_string(plan.output_field.as_deref());
    let agent_name = js_string(&module.agent.name);
    let description = module
        .agent
        .description
        .as_deref()
        .unwrap_or("AIR semantic agent");

    output.push_str("async function main() {\n");
    output.push_str("  const args = parseArgs(process.argv);\n");
    output.push_str("  const input = readJson(args.input);\n");
    output.push_str("  const modelConfig = readJson(args.modelConfig);\n");
    output.push_str(
        "  const toolConfig = args.toolConfig ? readJson(args.toolConfig) : { tools: {} };\n",
    );
    output.push_str(&format!(
        "  const modelAlias = args.modelAlias ?? {};\n",
        js_string(&plan.model_alias)
    ));
    output.push_str("  const model = configureOpenAICompatible(modelConfig, modelAlias);\n");
    output.push_str(&format!(
        "  const semanticTool = makeLocalDocsSearchTool(toolConfig, {});\n",
        tool_name_literal
    ));
    output.push_str("  const tools = semanticTool ? [semanticTool] : [];\n\n");
    output.push_str("  const agent = new Agent({\n");
    output.push_str(&format!("    name: {},\n", agent_name));
    output.push_str("    model: modelName(model),\n");
    output.push_str("    instructions:\n");
    output.push_str(&format!(
        "      `${{model.system_prompt ?? ''}}\\n\\n{}\\n` +\n",
        escape_template(description)
    ));
    if plan.tool_name.is_some() {
        output.push_str(&format!(
            "      'Call {} before the final answer when external knowledge is needed; avoid extra calls unless the first result is insufficient. ' +\n",
            sdk_tool_name
        ));
    }
    output.push_str(&format!(
        "      'Return only JSON matching this AIR output contract: {}.',\n",
        escape_single_quoted_js(&plan.output_contract)
    ));
    output.push_str("    tools,\n");
    output.push_str("    modelSettings: {\n");
    output.push_str("      temperature: model.temperature ?? 0,\n");
    output.push_str("      toolChoice: 'auto',\n");
    output.push_str("    },\n");
    output.push_str("  });\n\n");
    output.push_str(&format!(
        "  const prompt = typeof input === 'object' && input !== null && {} in input\n",
        primary_input
    ));
    output.push_str(&format!("    ? `${{input[{}]}}`\n", primary_input));
    output.push_str("    : JSON.stringify(input);\n");
    output.push_str("  const result = await run(agent, prompt, { maxTurns: 6 });\n");
    output.push_str("  const finalOutput = parseJsonish(result.finalOutput);\n");
    output.push_str(&format!(
        "  if ({output_field}) validateOutput(AIR_MODULE, {output_field}, finalOutput);\n"
    ));
    output.push_str("  console.log(JSON.stringify(finalOutput, null, 2));\n");
    output.push_str("}\n\n");
    output.push_str("main().catch((error) => {\n");
    output.push_str("  console.error(error);\n");
    output.push_str("  process.exitCode = 1;\n");
    output.push_str("});\n");
}

fn js_optional_string(value: Option<&str>) -> String {
    value.map(js_string).unwrap_or_else(|| "null".to_string())
}

fn js_string(value: &str) -> String {
    serde_json_escape(value)
}

fn serde_json_escape(value: &str) -> String {
    let mut output = String::from("\"");
    for ch in value.chars() {
        match ch {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            ch => output.push(ch),
        }
    }
    output.push('"');
    output
}

fn escape_template(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${")
}

fn to_sdk_tool_name(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch == '_' || ch.is_ascii_alphanumeric() {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn output_contract(module: &AirModule, return_output: Option<&str>) -> String {
    if let Some(output_name) = return_output {
        if let Some(spec) = module
            .outputs
            .get(output_name)
            .or_else(|| module.state.get(output_name))
        {
            return describe_type(spec);
        }
    }

    if module.outputs.is_empty() {
        return "any JSON value".to_string();
    }

    format!(
        "object with top-level keys [{}]",
        module
            .outputs
            .keys()
            .map(String::as_str)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn describe_type(spec: &TypeSpec) -> String {
    match spec {
        TypeSpec::Shorthand(kind) => kind.kind_name().to_string(),
        TypeSpec::Detailed(detailed) => match detailed.kind {
            DetailedTypeKind::Object => {
                if detailed.required.is_empty() && detailed.properties.is_empty() {
                    return "object".to_string();
                }

                let required = if detailed.required.is_empty() {
                    "no required keys".to_string()
                } else {
                    format!("required keys [{}]", detailed.required.join(", "))
                };
                let properties = if detailed.properties.is_empty() {
                    "any properties".to_string()
                } else {
                    let entries = detailed
                        .properties
                        .iter()
                        .map(|(name, spec)| format!("{name}: {}", describe_type(spec)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("properties {{{entries}}}")
                };
                format!("object with {required}; {properties}")
            }
            DetailedTypeKind::Array => detailed
                .items
                .as_deref()
                .map(|items| format!("array of {}", describe_type(items)))
                .unwrap_or_else(|| "array".to_string()),
            DetailedTypeKind::Enum => {
                if detailed.enum_values.is_empty() {
                    "enum".to_string()
                } else {
                    format!("enum [{}]", detailed.enum_values.join(", "))
                }
            }
            _ => detailed.kind.kind_name().to_string(),
        },
    }
}

fn escape_single_quoted_js(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn semantically_lowers_helpdesk_rag_to_openai_agents_js() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let module =
            air_parser::parse_air_file(root.join("examples/simple-helpdesk/helpdesk-rag.air.yaml"))
                .unwrap();

        let code = lower_module(&module).unwrap();

        assert!(code.contains("Generated by AIR OpenAI Agents JS semantic backend"));
        assert!(code.contains("const AIR_MODULE = {"));
        assert!(code.contains("function validateOutput"));
        assert!(code.contains("new Agent({"));
        assert!(code.contains("setOpenAIAPI('chat_completions')"));
        assert!(code.contains("makeLocalDocsSearchTool(toolConfig, \"docs.search\")"));
        assert!(code.contains("modelAlias = args.modelAlias ?? \"rag_answerer\""));
        assert!(code.contains("toolChoice: 'auto'"));
        assert!(code.contains("validateOutput(AIR_MODULE, \"answer\", finalOutput);"));
        assert!(code.contains("required keys [answer, citations, escalation_required]"));
        assert!(code.contains("spec.min_items != null"));
        assert!(code.contains("spec.max_items != null"));
    }

    #[test]
    fn strictly_lowers_run_plan_with_air_schema_validation_runtime() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let store = air_linker::parse_module_store_file(
            root.join("tests/plans/module-store.air-store.yaml"),
        )
        .unwrap();
        let plan = air_linker::parse_run_plan_file(
            root.join("tests/plans/complex-escalation.air-plan.yaml"),
        )
        .unwrap();

        let code = lower_run_plan_strict(&plan, &store, &root).unwrap();

        assert!(code.contains("function validateOutput"));
        assert!(code.contains("async function callTool"));
        assert!(code.contains("throw new Error(`AIR schema violation: "));
        assert!(code.contains("validateOutput(module, action.output, resultValue);"));
        assert!(code.contains("resultValue = await callTool(toolConfig, action.tool, inputValue);"));
        assert!(code.contains("field.endsWith('[]')"));
        assert!(code.contains("inputs[field].push(value);"));
        assert!(code.contains("function loadDotEnv"));
        assert!(code.contains("loadDotEnv();"));
        assert!(code.contains("function normalizePath"));
        assert!(code.contains("path = normalizePath(path);"));
        assert!(code.contains("function validateRunPlanCapabilities"));
        assert!(code.contains("validateRunPlanCapabilities();"));
        assert!(code.contains("function checkModuleTimeout"));
        assert!(code.contains("policy.max_model_calls exceeded"));
        assert!(code.contains("policy.max_tool_calls exceeded"));
        assert!(code.contains("policy.max_repeated_tool_calls exceeded"));
        assert!(code.contains("action exceeded timeout_seconds"));
        assert!(code.contains("function validateToolCapability"));
        assert!(code.contains("function enforceRepeatedToolPolicy"));
        assert!(code.contains("provider capability"));
        assert!(code.contains("function validateApprovalCapabilities"));
        assert!(code.contains("async function requestApproval"));
        assert!(code.contains("approval is not wired for capability"));
        assert!(code.contains("approval denied for capability"));
        assert!(code.contains("function retryInput"));
        assert!(code.contains("function isTokenLimitError"));
        assert!(code.contains("function compactJsonValue"));
        assert!(code.contains("_air_retry"));
        assert!(code.contains("token_limit"));
        assert!(code.contains("max_attempts"));
        assert!(code.contains("function emitTrace"));
        assert!(code.contains("AIR_TRACE"));
        assert!(code.contains("model_call_start"));
        assert!(code.contains("dynamic_fanout"));
        assert!(code.contains("spec.min_items != null"));
        assert!(code.contains("spec.max_items != null"));
    }

    #[test]
    fn strict_runtime_supports_tool_dispatch_actions() {
        let mut code = String::new();
        push_strict_js_runtime(&mut code);

        assert!(code.contains("action.kind === 'tool_dispatch'"));
        assert!(code.contains("tool_dispatch input.tool must be a string"));
        assert!(code.contains("function normalizeModelSelectedToolName"));
        assert!(code.contains("await callTool(toolConfig, normalized.toolName, inputValue)"));
        assert!(code.contains("action: 'tool_dispatch_start'"));
    }

    #[test]
    fn strict_runtime_supports_tool_batch_dispatch_actions() {
        let mut code = String::new();
        push_strict_js_runtime(&mut code);

        assert!(code.contains("action.kind === 'tool_batch_dispatch'"));
        assert!(code.contains("tool_batch_dispatch input must be an array"));
        assert!(code.contains("tool_batch_dispatch max_calls exceeded"));
        assert!(code.contains("tool_batch_dispatch_item_start"));
        assert!(code.contains("batchOutputs.push"));
        assert!(code.contains("requested_tool"));
        assert!(code.contains("const observeErrors = action.on_error === 'observe'"));
        assert!(code.contains("status: 'error'"));
        assert!(code.contains("is not declared by module"));
        assert!(code.contains("tool: '<invalid>'"));
        assert!(code.contains(
            "enforceRepeatedToolPolicy(module, toolHistory, normalized.toolName, inputValue);"
        ));
        assert!(code.contains(
            "if (observeErrors) {\n              const message = String(error?.message ?? error);"
        ));
        assert!(code.contains("function runtimeContext"));
        assert!(code.contains("localState._air = runtimeContext"));
    }

    #[test]
    fn strictly_lowers_compound_conditions_to_runtime() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let store = air_linker::ModuleStore {
            store: air_linker::StoreMetadata {
                name: "test-store".to_string(),
                version: "0.1.0".to_string(),
            },
            imports: Vec::new(),
            modules: BTreeMap::from([(
                "test.conditional_loop@0.1.0".to_string(),
                air_linker::ModuleRef {
                    path: "tests/agents/conditional-loop.air.yaml".into(),
                    kind: air_linker::ModuleKind::Primitive,
                    visibility: air_linker::ModuleVisibility::Internal,
                    description: None,
                    tags: Vec::new(),
                    covers: Vec::new(),
                    priority: 0,
                },
            )]),
            recipes: Vec::new(),
        };
        let plan = air_linker::RunPlan {
            plan: air_linker::RunPlanMetadata {
                name: "conditional-loop".to_string(),
                version: "0.1.0".to_string(),
            },
            requires: air_core::Requirements::default(),
            nodes: vec![air_linker::RunPlanNode {
                id: "loop".to_string(),
                module: "test.conditional_loop@0.1.0".to_string(),
                when: None,
            }],
            entry: "loop".to_string(),
            edges: Vec::new(),
            connect: vec![air_linker::Connection {
                from: Some("$input.question".to_string()),
                to: "loop.question".to_string(),
                value: None,
            }],
            outputs: BTreeMap::from([("decision".to_string(), "loop.decision".to_string())]),
            halts: Vec::new(),
            decisions: Vec::new(),
            schedule: None,
            dynamic: None,
        };

        let code = lower_run_plan_strict(&plan, &store, &root).unwrap();

        assert!(code.contains("function conditionMatches"));
        assert!(code.contains("phase == \\\"route\\\" && decision.complete == false"));
        assert!(code.contains(
            "workflow.rules.find((candidate) => conditionMatches(localState, outputs, candidate.when))"
        ));
        assert!(!code.contains("function phase"));
    }

    #[test]
    fn strictly_lowers_dynamic_run_plan_with_air_dynamic_runtime() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let store = air_linker::parse_module_store_file(
            root.join("examples/deep-research/module-store.air-store.yaml"),
        )
        .unwrap();
        let plan = air_linker::parse_run_plan_file(
            root.join("examples/deep-research/deep-research-dynamic.air-plan.yaml"),
        )
        .unwrap();

        let code = lower_run_plan_strict(&plan, &store, &root).unwrap();

        assert!(code.contains("async function runDynamicAfter"));
        assert!(code.contains("async function runDynamicFanout"));
        assert!(code.contains("\"deep_research.research_topic@0.1.0\""));
        assert!(code.contains("await runDynamicAfter(state, modelConfig, toolConfig, moduleId);"));
    }
}
