[package]
name = "air-tools"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
air-core = { path = "../air-core" }
air-runtime = { path = "../air-runtime" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
regex.workspace = true
globset.workspace = true
